//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeaTransportationEntities : DbContext
    {
        public SeaTransportationEntities()
            : base("name=SeaTransportationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BS_City> BS_City { get; set; }
        public virtual DbSet<SYS_Bracket> SYS_Bracket { get; set; }
        public virtual DbSet<SYS_Calculate> SYS_Calculate { get; set; }
        public virtual DbSet<SYS_Charge> SYS_Charge { get; set; }
        public virtual DbSet<SYS_Chauffeur> SYS_Chauffeur { get; set; }
        public virtual DbSet<SYS_Client> SYS_Client { get; set; }
        public virtual DbSet<SYS_ClientScontacts> SYS_ClientScontacts { get; set; }
        public virtual DbSet<SYS_ClientSite> SYS_ClientSite { get; set; }
        public virtual DbSet<SYS_ClientType> SYS_ClientType { get; set; }
        public virtual DbSet<SYS_CloseAccount> SYS_CloseAccount { get; set; }
        public virtual DbSet<SYS_Commercel> SYS_Commercel { get; set; }
        public virtual DbSet<SYS_Customs> SYS_Customs { get; set; }
        public virtual DbSet<SYS_Department> SYS_Department { get; set; }
        public virtual DbSet<SYS_DriverBook> SYS_DriverBook { get; set; }
        public virtual DbSet<SYS_Etrust> SYS_Etrust { get; set; }
        public virtual DbSet<SYS_Expense> SYS_Expense { get; set; }
        public virtual DbSet<SYS_Gatedot> SYS_Gatedot { get; set; }
        public virtual DbSet<SYS_HaulWay> SYS_HaulWay { get; set; }
        public virtual DbSet<SYS_Jurisdiction> SYS_Jurisdiction { get; set; }
        public virtual DbSet<SYS_Mention> SYS_Mention { get; set; }
        public virtual DbSet<SYS_Message> SYS_Message { get; set; }
        public virtual DbSet<SYS_Offer> SYS_Offer { get; set; }
        public virtual DbSet<SYS_OfferDetail> SYS_OfferDetail { get; set; }
        public virtual DbSet<SYS_Parities> SYS_Parities { get; set; }
        public virtual DbSet<SYS_PayWay> SYS_PayWay { get; set; }
        public virtual DbSet<SYS_Port> SYS_Port { get; set; }
        public virtual DbSet<SYS_SettleWay> SYS_SettleWay { get; set; }
        public virtual DbSet<SYS_Ship> SYS_Ship { get; set; }
        public virtual DbSet<SYS_Sign> SYS_Sign { get; set; }
        public virtual DbSet<SYS_SignCloseAccount> SYS_SignCloseAccount { get; set; }
        public virtual DbSet<SYS_Staff> SYS_Staff { get; set; }
        public virtual DbSet<SYS_User> SYS_User { get; set; }
        public virtual DbSet<SYS_VehicleInformation> SYS_VehicleInformation { get; set; }
    }
}
