//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ClientSite
    {
        public int ClientSiteID { get; set; }
        public int ClientID { get; set; }
        public int GatedotID { get; set; }
        public string ContactsPhone { get; set; }
        public string ContactsName { get; set; }
        public string ClientSite { get; set; }
        public string Remark { get; set; }
        public string FactoryName { get; set; }
        public string FactoryCode { get; set; }
    }
}
