//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_OfferDetail
    {
        public int OfferDetailID { get; set; }
        public int OfferID { get; set; }
        public int ExpenseID { get; set; }
        public int HaulWayID { get; set; }
        public string EtryClasses { get; set; }
        public string CabinetType { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<int> ClientSiteID { get; set; }
        public string WorkCategory { get; set; }
        public string BoxQuantity { get; set; }
        public string Remark { get; set; }
        public string Currency { get; set; }
        public Nullable<int> StaffID { get; set; }
    }
}
