//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Calculate
    {
        public int CalculateID { get; set; }
        public Nullable<int> SignID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string CalculateNumber { get; set; }
        public string SettleAccounts { get; set; }
        public short PayWayID { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> SFMoney { get; set; }
        public Nullable<System.DateTime> SFDate { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string ChequeNumber { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> AlreadyCancelMoney { get; set; }
        public Nullable<decimal> StayCancelMoney { get; set; }
        public Nullable<short> MessageID { get; set; }
    }
}
