//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Message
    {
        public short MessageID { get; set; }
        public string TissueCode { get; set; }
        public string ChineseName { get; set; }
        public string ChineseAbbreviation { get; set; }
        public string EnglishCode { get; set; }
        public string EnglishName { get; set; }
        public string Site { get; set; }
        public string Relation { get; set; }
        public string Describe { get; set; }
    }
}
