//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Offer
    {
        public int OfferID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string OfferType { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
        public Nullable<System.DateTime> TakeEffectDate { get; set; }
        public Nullable<System.DateTime> LoseEfficacyDate { get; set; }
        public bool WhetherShui { get; set; }
        public string Remark { get; set; }
    }
}
