//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Etrust
    {
        public int EtrustID { get; set; }
        public int StaffID { get; set; }
        public Nullable<int> ClientTypeID { get; set; }
        public Nullable<int> CustomsID { get; set; }
        public Nullable<int> ShipID { get; set; }
        public Nullable<int> PortID { get; set; }
        public short MessageID { get; set; }
        public Nullable<int> UndertakeID { get; set; }
        public Nullable<int> VehicleInformationID { get; set; }
        public string EtrustNmber { get; set; }
        public string WorkCategory { get; set; }
        public string CheXing { get; set; }
        public string EtryClasses { get; set; }
        public string ClientCode { get; set; }
        public Nullable<int> ClientScontactsID { get; set; }
        public string ClientMobile { get; set; }
        public Nullable<System.DateTime> PlanHandTime { get; set; }
        public bool WhetherShou { get; set; }
        public Nullable<decimal> CollectionMoney { get; set; }
        public string HuoZhuName { get; set; }
        public string IndentNumber { get; set; }
        public Nullable<int> ClientSiteID { get; set; }
        public string TradeClause { get; set; }
        public Nullable<int> ChargeCustomsID { get; set; }
        public Nullable<System.DateTime> ArriveTime { get; set; }
        public Nullable<int> TiGuiDiDianID { get; set; }
        public Nullable<int> HuaiGuiDiDianID { get; set; }
        public string CargoWeight { get; set; }
        public Nullable<System.DateTime> HuiChangTime { get; set; }
        public string HangCi { get; set; }
        public Nullable<System.DateTime> KaiCangTime { get; set; }
        public Nullable<int> GoalHarborID { get; set; }
        public string ZuoJianWay { get; set; }
        public Nullable<System.DateTime> JieGuanTime { get; set; }
        public Nullable<int> CustomsBrokerID { get; set; }
        public string EtryWay { get; set; }
        public bool WhetherBen { get; set; }
        public Nullable<int> FGCustomsID { get; set; }
        public string AssistBusiness { get; set; }
        public string CargoClassify { get; set; }
        public bool WhetherShui { get; set; }
        public Nullable<decimal> ManagementFee { get; set; }
        public string SpecialNeed { get; set; }
        public string AttentionMatter { get; set; }
        public string CabinetType { get; set; }
        public string BookingSpace { get; set; }
        public string Cupboard { get; set; }
        public string Seal { get; set; }
        public string AuditType { get; set; }
        public string CarriageNumber { get; set; }
        public Nullable<System.DateTime> PaiCheDate { get; set; }
        public string PaiCheExplain { get; set; }
        public Nullable<System.DateTime> DispatchTime { get; set; }
        public Nullable<System.DateTime> TiKGuiTime { get; set; }
        public Nullable<System.DateTime> ArriveFactoryTime { get; set; }
        public Nullable<System.DateTime> LeftFactoryTime { get; set; }
        public Nullable<System.DateTime> HuaiWeightTime { get; set; }
        public Nullable<System.DateTime> FollowTime { get; set; }
        public string EtrustType { get; set; }
        public Nullable<decimal> ShuiBl { get; set; }
        public Nullable<int> OfferDetailID { get; set; }
        public string OddNumber { get; set; }
        public string FollowExplain { get; set; }
    }
}
