//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Chauffeur
    {
        public int ChauffeurID { get; set; }
        public short MessageID { get; set; }
        public string ChauffeurName { get; set; }
        public string ChauffeurNumber { get; set; }
        public string Sex { get; set; }
        public string EnglishName { get; set; }
        public byte[] Picture { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public int ClientTypeID { get; set; }
        public string HealthCondition { get; set; }
        public string IdentityCard { get; set; }
        public string PhoneOne { get; set; }
        public string PhoneTwo { get; set; }
        public string HongkongPhoneOne { get; set; }
        public string HongkongPhoneTwo { get; set; }
        public string FamilyPhone { get; set; }
        public string UrgencyRelationer { get; set; }
        public string UrgencyRelationerPhone { get; set; }
        public string UrgencyRelationerSite { get; set; }
        public Nullable<decimal> CashDeposit { get; set; }
        public Nullable<decimal> DeductRatio { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string DrivingLicence { get; set; }
        public Nullable<System.DateTime> Jsznsrq { get; set; }
        public Nullable<System.DateTime> Jszyxrq { get; set; }
        public string Hkjszh { get; set; }
        public Nullable<System.DateTime> Hkjszhnsrq { get; set; }
        public Nullable<System.DateTime> Hkjszhlyrq { get; set; }
        public string ICNumber { get; set; }
        public Nullable<System.DateTime> ICNsrq { get; set; }
        public string Hxzh { get; set; }
        public string StatusCard { get; set; }
        public Nullable<System.DateTime> StatusCardNsrq { get; set; }
        public string SocialSecurityCardNumber { get; set; }
        public string CertificateQualification { get; set; }
        public Nullable<System.DateTime> CertificateQualificationNsrq { get; set; }
        public string WorkLicense { get; set; }
        public Nullable<System.DateTime> WorkLicenseNsrq { get; set; }
        public bool FenGSKJ { get; set; }
        public bool WhetherStart { get; set; }
        public string Apartment { get; set; }
        public string RegisteredPermanent { get; set; }
        public string HongKongPermanent { get; set; }
        public string Describe { get; set; }
    }
}
