//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_VehicleInformation
    {
        public int VehicleInformationID { get; set; }
        public int ChauffeurID { get; set; }
        public int BracketID { get; set; }
        public short MessageID { get; set; }
        public string VehicleCode { get; set; }
        public string PlateNumbers { get; set; }
        public string HongKongPlateNumber { get; set; }
        public string VehicleClass { get; set; }
        public string MotorcycleType { get; set; }
        public string VehicleType { get; set; }
        public string Usualplace { get; set; }
    }
}
