//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Ship
    {
        public int ShipID { get; set; }
        public int ClientTypeID { get; set; }
        public string ShipCode { get; set; }
        public string ChineseName { get; set; }
        public string EnglishName { get; set; }
        public string Abbreviation { get; set; }
        public string ShipEast { get; set; }
        public string ShipType { get; set; }
        public string CaptainName { get; set; }
        public string ShipMobile { get; set; }
        public bool WhetherStart { get; set; }
        public string Operator { get; set; }
    }
}
