//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Client
    {
        public int ClientID { get; set; }
        public int GatedotID { get; set; }
        public Nullable<short> MessageID { get; set; }
        public int StaffID { get; set; }
        public string ClientCode { get; set; }
        public string ClientAbbreviation { get; set; }
        public string ChineseName { get; set; }
        public string ClientRank { get; set; }
        public string CustomsCode { get; set; }
        public string ClientSource { get; set; }
        public string ClientPhone { get; set; }
        public string ClientFax { get; set; }
        public string Email { get; set; }
        public Nullable<System.TimeSpan> OfficeHours { get; set; }
        public Nullable<System.TimeSpan> ClosingTime { get; set; }
        public string PostCode { get; set; }
        public string Site { get; set; }
        public string Website { get; set; }
        public string OpenAccount { get; set; }
        public string OpenAccountCode { get; set; }
        public string Describe { get; set; }
        public bool WhetherStart { get; set; }
    }
}
