//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_HaulWay
    {
        public int HaulWayID { get; set; }
        public Nullable<int> MentionAreaID { get; set; }
        public string HaulWayDescription { get; set; }
        public Nullable<int> LoadingAreaID { get; set; }
        public Nullable<int> CustomsAreaID { get; set; }
        public Nullable<int> AlsoTankAreaID { get; set; }
        public Nullable<decimal> OutwardVoyage { get; set; }
        public Nullable<decimal> ReturnTrip { get; set; }
        public Nullable<decimal> OutwardVoyageFree { get; set; }
        public Nullable<decimal> ReturnTripFree { get; set; }
        public Nullable<decimal> OutwardVoyageTime { get; set; }
        public Nullable<decimal> ReturnTripTime { get; set; }
        public Nullable<decimal> TotalTime { get; set; }
        public bool WhetherStart { get; set; }
        public string Describe { get; set; }
    }
}
