//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Mention
    {
        public int MentionID { get; set; }
        public int GatedotID { get; set; }
        public string MCode { get; set; }
        public string Abbreviation { get; set; }
        public string Linkman { get; set; }
        public string Mobile { get; set; }
        public string Site { get; set; }
        public bool WhetherStart { get; set; }
        public Nullable<decimal> HangCharge { get; set; }
        public Nullable<decimal> CheckFee { get; set; }
        public Nullable<decimal> GateCharges { get; set; }
    }
}
