//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Staff
    {
        public int StaffID { get; set; }
        public int DepartmentID { get; set; }
        public string StaffName { get; set; }
        public string StaffNumber { get; set; }
        public string State { get; set; }
        public string Duty { get; set; }
        public string Sex { get; set; }
        public string CultureLevel { get; set; }
        public Nullable<System.DateTime> JoinJob { get; set; }
        public bool WhetherStart { get; set; }
    }
}
