//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Sign
    {
        public int SignID { get; set; }
        public int SignCloseAccountID { get; set; }
        public Nullable<decimal> BCYShou { get; set; }
        public Nullable<decimal> BCYFu { get; set; }
        public Nullable<decimal> SettleMoney { get; set; }
        public string SignExplain { get; set; }
        public string SettleNumber { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public Nullable<System.DateTime> YuSettleDate { get; set; }
        public short SettleWayID { get; set; }
        public short PayWayID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string FinishType { get; set; }
        public string SignType { get; set; }
    }
}
