//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Customs
    {
        public int CustomsID { get; set; }
        public int GatedotID { get; set; }
        public string CustomsName { get; set; }
        public string CustomsCode { get; set; }
        public string EnglishName { get; set; }
        public string MobilePhone { get; set; }
        public string Mobile { get; set; }
        public string Linkman { get; set; }
        public string Email { get; set; }
        public string Faxes { get; set; }
        public string PostCode { get; set; }
        public Nullable<System.TimeSpan> OfficeHours { get; set; }
        public Nullable<System.TimeSpan> ClosingTime { get; set; }
        public string Site { get; set; }
        public string Website { get; set; }
        public bool WhetherStart { get; set; }
        public string Describe { get; set; }
    }
}
